services:
  webserver:
    image: gekone87/docker_symfony_dev
    container_name: docker_zlabel
    volumes:
      - ./main_sites:/var/www/html/
    ports:
      - "8888:80"
    expose:
      - "9000"

    #network_mode: host
      #web:
      #  image: nginx:latest
      #  ports:
      #    - "8888:80"
      #  volumes:
      #- ./main_sites:/var/www/main_sites
  #    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  #  depends_on:
  #    - php
  #mysql:
  #  image: mysql:5.6
  #  environment:
  #    MYSQL_ROOT_PASSWORD: symf0ny
  #  ports:
  #    - "3333:3306"
